export const API_ROUTE_CONTRACT = [
  {
    operationId: "authGet",
    method: "GET",
    path: "/api/auth/[...all]",
    file: "src/app/api/auth/[...all]/route.ts",
    auth: "public",
    payment: "none",
    resource: "auth",
    description: "Better Auth protocol endpoint.",
  },
  {
    operationId: "authPost",
    method: "POST",
    path: "/api/auth/[...all]",
    file: "src/app/api/auth/[...all]/route.ts",
    auth: "public",
    payment: "none",
    resource: "auth",
    description: "Better Auth protocol endpoint.",
  },
  {
    operationId: "updateWallet",
    method: "POST",
    path: "/api/me/wallet",
    file: "src/app/api/me/wallet/route.ts",
    auth: "required",
    payment: "none",
    resource: "user",
    description: "Store a future payout destination preference.",
  },
  {
    operationId: "createRfs",
    method: "POST",
    path: "/api/rfs",
    file: "src/app/api/rfs/route.ts",
    auth: "required",
    payment: "none",
    resource: "rfs",
    description: "Create a marketplace research request.",
  },
  {
    operationId: "getRfs",
    method: "GET",
    path: "/api/rfs/[id]",
    file: "src/app/api/rfs/[id]/route.ts",
    auth: "public",
    payment: "none",
    resource: "rfs",
    description: "Read public request metadata.",
  },
  {
    operationId: "claimRfs",
    method: "POST",
    path: "/api/rfs/[id]/claim",
    file: "src/app/api/rfs/[id]/claim/route.ts",
    auth: "required",
    payment: "none",
    resource: "rfs",
    description: "Claim a funded request as its researcher.",
  },
  {
    operationId: "fundRfs",
    method: "POST",
    path: "/api/rfs/[id]/fund",
    file: "src/app/api/rfs/[id]/fund/route.ts",
    auth: "optional",
    payment: "mpp",
    resource: "contribution",
    description: "Fund an open request through MPP on Tempo Moderato.",
  },
  {
    operationId: "submitSkill",
    method: "POST",
    path: "/api/rfs/[id]/submit",
    file: "src/app/api/rfs/[id]/submit/route.ts",
    auth: "required",
    payment: "none",
    resource: "skill",
    description: "Publish the claimed request's skill.",
  },
  {
    operationId: "listMarketplace",
    method: "GET",
    path: "/api/skills",
    file: "src/app/api/skills/route.ts",
    auth: "public",
    payment: "none",
    resource: "marketplace",
    description: "List bounded public request and skill metadata.",
  },
  {
    operationId: "getSkill",
    method: "GET",
    path: "/api/skills/[id]",
    file: "src/app/api/skills/[id]/route.ts",
    auth: "optional",
    payment: "none",
    resource: "skill",
    description: "Read public skill metadata and viewer capabilities.",
  },
  {
    operationId: "readSkillContent",
    method: "GET",
    path: "/api/skills/[id]/content",
    file: "src/app/api/skills/[id]/content/route.ts",
    auth: "optional",
    payment: "mpp",
    resource: "skill-content",
    description: "Read entitled content or purchase one-shot access through MPP.",
  },
] as const;

export type ApiRouteContract = (typeof API_ROUTE_CONTRACT)[number];
export type ApiOperationId = ApiRouteContract["operationId"];
