import { anyApi } from "convex/server";
import { fetchAuthQuery, getAuthenticationStatus } from "@/lib/auth-server";
import { toJsonValue } from "@/lib/json";
import { WorkspaceState } from "@/components/workspace-state";
import { AdjudicationControls } from "@/components/adjudication-controls";

export const dynamic = "force-dynamic";
type Row = { disputeId: string; rfsId: string; rfsTitle: string; triggerType: string; state: string; dueAt: number; stickyHold: boolean; criteria: Array<{ criterionId: string; title: string; weightBps: number; passCondition: string }>; evidence: Array<{ artifactId: string; publicRedaction: string }> };
export default async function AdjudicationsPage() { if (await getAuthenticationStatus() !== "authenticated") return <WorkspaceState title="Adjudications" message="Sign in with a security adjudicator account." signInPath="/review/adjudications" />; let rows: Row[]; try { rows = toJsonValue(await fetchAuthQuery(anyApi.evaluationV2.listAdjudicationQueue, {})) as Row[]; } catch { return <WorkspaceState title="Adjudications" message="An active security adjudicator role is required." />; } return <main><h1 className="text-xl font-medium">Adjudications</h1><p className="mt-1 text-sm text-muted-foreground">Permanent adverse decisions require an independent human and a public redaction.</p><div className="mt-6 space-y-8">{rows.map((row) => <article key={row.disputeId} className="border-t border-border pt-5"><div className="grid gap-2 sm:grid-cols-[1fr_auto]"><div><h2 className="font-medium">{row.rfsTitle}</h2><p className="font-mono text-xs text-muted-foreground break-all">{row.triggerType} · {row.disputeId}</p></div><div className="font-mono text-xs sm:text-right"><p>{row.state}{row.stickyHold ? " · funds held" : ""}</p><p className="text-muted-foreground">due {new Date(row.dueAt).toLocaleString()}</p></div></div>{row.evidence.map((item) => <p key={item.artifactId} className="mt-2 text-sm">Evidence {item.artifactId}: {item.publicRedaction}</p>)}<AdjudicationControls disputeId={row.disputeId} state={row.state} criteria={row.criteria} /></article>)}{rows.length === 0 ? <p className="text-sm text-muted-foreground">No active adjudications.</p> : null}</div></main>; }
