"use client";

import { useCallback, useEffect, useState } from "react";

const permissions = ["rfs:read", "rfs:write", "fund", "apply", "submit", "evaluate", "purchase", "settlement:read"] as const;
const input = "h-9 w-full border border-border bg-white px-3 font-mono text-sm";

const command = async (path: string, body: unknown) => await fetch(path, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: JSON.stringify(body) });

export function AgentManager() {
  const [keys, setKeys] = useState<Record<string, unknown>[]>([]);
  const [selected, setSelected] = useState<string[]>(["rfs:read", "apply", "submit", "evaluate"]);
  const [secret, setSecret] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { const response = await fetch("/api/v2/me/agent-keys", { cache: "no-store" }); const payload = await response.json(); if (response.ok && Array.isArray(payload.data)) setKeys(payload.data); }, []);
  useEffect(() => {
    let active = true;
    void fetch("/api/v2/me/agent-keys", { cache: "no-store" }).then(async (response) => {
      const payload = await response.json();
      if (active && response.ok && Array.isArray(payload.data)) setKeys(payload.data);
    });
    return () => { active = false; };
  }, []);
  const create = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setMessage(null); const fields = new FormData(event.currentTarget); const response = await command("/api/v2/me/agent-keys", { name: fields.get("name"), expiresIn: Number(fields.get("expiresIn")), permissions: selected }); const payload = await response.json(); if (!response.ok) return setMessage(payload.message ?? "Agent key creation failed."); setSecret(payload.data?.key ?? null); setMessage("Agent key created and bound to this principal."); await load(); };
  const revoke = async (keyId: string) => { const response = await command("/api/v2/me/agent-keys/revoke", { keyId }); const payload = await response.json(); setMessage(response.ok ? "Agent key revoked." : payload.message ?? "Revocation failed."); await load(); };
  const delegate = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const fields = new FormData(event.currentTarget); const chosen = selected; const body = { apiKeyId: fields.get("apiKeyId"), name: fields.get("delegationName"), permissions: chosen, actions: chosen, resourceAllowlist: [], tagAllowlist: [], perTransactionCapBaseUnits: fields.get("perTransactionCapBaseUnits") || undefined, rolling24HourCapBaseUnits: fields.get("rolling24HourCapBaseUnits") || undefined, lifetimeCapBaseUnits: fields.get("lifetimeCapBaseUnits") || undefined, expiresAt: Date.now() + 30 * 24 * 60 * 60 * 1000 }; const response = await command("/api/v2/me/delegations", body); const payload = await response.json(); setMessage(response.ok ? `Approval requested: ${payload.data?.requestId}` : payload.message ?? "Delegation request failed."); };
  return <div className="space-y-10"><section><h2 className="border-b border-border pb-2 font-medium">Agent keys</h2><form onSubmit={create} className="mt-4 grid gap-3 sm:grid-cols-[1fr_10rem_auto]"><label className="grid gap-1 font-mono text-xs">Name<input required name="name" className={input} /></label><label className="grid gap-1 font-mono text-xs">Expires in seconds<input required name="expiresIn" type="number" min="60" defaultValue="7776000" className={input} /></label><button className="self-end h-9 border border-foreground px-4 font-mono text-sm">create</button><fieldset className="sm:col-span-3"><legend className="font-mono text-xs">Permissions</legend><div className="mt-2 flex flex-wrap gap-3">{permissions.map((permission) => <label key={permission} className="flex items-center gap-1.5 font-mono text-xs"><input type="checkbox" checked={selected.includes(permission)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, permission] : current.filter((item) => item !== permission))} />{permission}</label>)}</div></fieldset></form>{secret ? <div role="status" className="mt-4 border-2 border-amber-600 bg-amber-50 p-3"><p className="font-mono text-xs font-semibold uppercase">Shown once</p><code className="mt-2 block break-all text-sm">{secret}</code></div> : null}<div className="mt-4">{keys.map((key) => { const keyId = typeof key.id === "string" ? key.id : ""; return <div key={keyId} className="flex flex-wrap items-center justify-between gap-3 border-b border-border py-3 text-sm"><div><span className="font-medium">{typeof key.name === "string" ? key.name : "unnamed"}</span><code className="ml-3 text-xs text-muted-foreground">{keyId}</code></div><button onClick={() => void revoke(keyId)} className="font-mono text-xs underline">revoke</button></div>; })}</div></section><section><h2 className="border-b border-border pb-2 font-medium">Delegation bounds</h2><form onSubmit={delegate} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="grid gap-1 font-mono text-xs">Agent key ID<input required name="apiKeyId" className={input} /></label><label className="grid gap-1 font-mono text-xs">Delegation name<input required name="delegationName" className={input} /></label><label className="grid gap-1 font-mono text-xs">Per transaction base units<input name="perTransactionCapBaseUnits" className={input} /></label><label className="grid gap-1 font-mono text-xs">Rolling 24h base units<input name="rolling24HourCapBaseUnits" className={input} /></label><label className="grid gap-1 font-mono text-xs">Lifetime base units<input name="lifetimeCapBaseUnits" className={input} /></label><button className="self-end h-9 border border-foreground px-4 font-mono text-sm">request approval</button></form></section>{message ? <p role="status" className="border border-border p-3 font-mono text-xs">{message}</p> : null}</div>;
}
