"use client";

import { useState } from "react";
import { authClient } from "@/lib/auth-client";

export function HumanActions({ actions }: { actions: Record<string, unknown>[] }) {
  const [message, setMessage] = useState<string | null>(null);
  const reauthenticate = async () => { const result = await authClient.signIn.passkey(); setMessage(result.error ? result.error.message ?? "Passkey verification failed." : "Passkey verified. Privileged actions are available for ten minutes."); };
  const decide = async (actionId: string, decision: "approve" | "decline") => { const response = await fetch(`/api/v2/me/human-actions/${actionId}/${decision}`, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: "{}" }); const payload = await response.json(); setMessage(response.ok ? `Action ${decision}d.` : payload.message ?? "Decision failed."); if (response.ok) location.reload(); };
  return <div><button onClick={() => void reauthenticate()} className="border border-foreground px-3 py-2 font-mono text-sm">verify passkey</button><div className="mt-5">{actions.map((action) => { const id = typeof action._id === "string" ? action._id : typeof action.id === "string" ? action.id : ""; return <article key={id} className="border-b border-border py-4"><div className="grid gap-2 text-sm sm:grid-cols-[10rem_1fr]"><span className="font-mono text-xs text-muted-foreground">type</span><span>{String(action.actionType ?? "unknown")}</span><span className="font-mono text-xs text-muted-foreground">resource</span><code>{String(action.resourceType ?? "resource")}:{String(action.resourceId ?? "")}</code><span className="font-mono text-xs text-muted-foreground">digest</span><code className="break-all">{String(action.payloadDigest ?? "")}</code><span className="font-mono text-xs text-muted-foreground">reason</span><span>{String(action.reason ?? "")}</span><span className="font-mono text-xs text-muted-foreground">expires</span><span>{typeof action.expiresAt === "number" ? new Date(action.expiresAt).toLocaleString() : "unknown"}</span></div><div className="mt-4 flex gap-3"><button onClick={() => void decide(id, "approve")} className="border border-foreground px-3 py-1.5 font-mono text-xs">approve</button><button onClick={() => void decide(id, "decline")} className="px-3 py-1.5 font-mono text-xs underline">decline</button></div></article>; })}{actions.length === 0 ? <p className="py-5 text-sm text-muted-foreground">No pending human actions.</p> : null}</div>{message ? <p role="status" className="mt-4 border border-border p-3 font-mono text-xs">{message}</p> : null}</div>;
}
