"use client";

import { useState } from "react";

const input = "h-9 w-full border border-border bg-white px-3 font-mono text-sm";
const post = async (path: string, body: unknown) => await fetch(path, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: JSON.stringify(body) });

export function WalletManager({ wallets }: { wallets: Record<string, unknown>[] }) {
  const [challenge, setChallenge] = useState<Record<string, unknown> | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const create = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const fields = new FormData(event.currentTarget); const response = await post("/api/v2/me/wallet-challenges", { address: fields.get("address"), chainId: Number(fields.get("chainId")) }); const payload = await response.json(); if (response.ok) setChallenge(payload.data); else setMessage(payload.message); };
  const confirm = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!challenge) return; const fields = new FormData(event.currentTarget); const response = await post("/api/v2/me/wallets", { challengeId: challenge.challengeId, message: challenge.message, signature: fields.get("signature"), makePrimary: fields.get("primary") === "on" }); const payload = await response.json(); setMessage(response.ok ? "Wallet verified." : payload.message ?? "Wallet verification failed."); if (response.ok) location.reload(); };
  return <div className="space-y-8"><section><h2 className="border-b border-border pb-2 font-medium">Verified wallets</h2>{wallets.map((wallet, index) => <article key={String(wallet.walletId ?? index)} className="grid gap-2 border-b border-border py-4 sm:grid-cols-[1fr_auto]"><div><p className="font-mono text-sm break-all">{String(wallet.address ?? "")}</p><p className="mt-1 text-xs text-muted-foreground">chain {String(wallet.chainId ?? "unknown")} · {String(wallet.verificationMethod ?? "signature proof")}</p></div><div className="font-mono text-xs sm:text-right"><p>{wallet.primary ? "primary" : "verified"}</p><p className="text-muted-foreground">{String(wallet.state ?? "active")}</p></div></article>)}{wallets.length === 0 ? <p className="py-4 text-sm text-muted-foreground">No verified wallets.</p> : null}</section><section><h2 className="border-b border-border pb-2 font-medium">Add wallet</h2><form onSubmit={create} className="mt-4 grid gap-3 sm:grid-cols-[1fr_8rem_auto]"><label className="grid gap-1 font-mono text-xs">Address<input required name="address" className={input} /></label><label className="grid gap-1 font-mono text-xs">Chain ID<input required name="chainId" type="number" className={input} /></label><button className="self-end h-9 border border-foreground px-4 font-mono text-sm">challenge</button></form>{challenge ? <form onSubmit={confirm} className="mt-5 border border-border p-4"><p className="whitespace-pre-wrap break-all font-mono text-xs">{String(challenge.message ?? "")}</p><label className="mt-4 grid gap-1 font-mono text-xs">Signature<input required name="signature" className={input} /></label><label className="mt-3 flex items-center gap-2 font-mono text-xs"><input type="checkbox" name="primary" />make primary for future intents</label><button className="mt-4 border border-foreground px-4 py-2 font-mono text-sm">verify signature</button></form> : null}</section><div className="border-l-2 border-amber-600 pl-3 text-sm text-muted-foreground">Existing obligations retain their immutable destination snapshot. Wallet rotation affects only future intents and obligations.</div>{message ? <p role="status" className="border border-border p-3 font-mono text-xs">{message}</p> : null}</div>;
}
