import { z } from "zod";

import {
  activityEventSchema,
  applicationSchema,
  bondIntentSchema,
  capabilitySchema,
  criterionSchema,
  errorEnvelopeSchema,
  evaluationSchema,
  evidenceVerificationSchema,
  fixtureRegistrationSchema,
  fixtureUploadIntentSchema,
  fundingIntentSchema,
  operationSchema,
  purchaseIntentSchema,
  postUseReviewSchema,
  rfsDraftSchema,
  successEnvelopeSchema,
} from "./schemas/common";

const command = (summary: string, schema?: z.ZodType, stateSensitive = false) => ({
  summary,
  parameters: [{ name: "Idempotency-Key", in: "header", required: true, schema: { type: "string" } }, ...(stateSensitive ? [{ name: "If-Match", in: "header", required: true, schema: { type: "integer", minimum: 1 }, description: "Current resourceVersion from the latest read." }] : [])],
  ...(schema ? { requestBody: { required: true, content: { "application/json": { schema: z.toJSONSchema(schema) } } } } : {}),
  responses: { "200": { description: "Success", content: { "application/json": { schema: { $ref: "#/components/schemas/Success" } } } }, "201": { description: "Created", content: { "application/json": { schema: { $ref: "#/components/schemas/Success" } } } }, "202": { description: "Accepted", content: { "application/json": { schema: { $ref: "#/components/schemas/Success" } } } }, "400": { description: "Invalid request", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } }, "401": { description: "Authentication required", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } }, "403": { description: "Forbidden", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } }, "409": { description: "Conflict or stale resource", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } }, "429": { description: "Rate limited", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } } },
  security: [{ apiKey: [] }, { cookieSession: [] }],
});
const queryParameter = (name: string, description: string, schema: Record<string, unknown>) => ({ name, in: "query", required: false, description, schema });
const catalogParameters = [
  queryParameter("category", "Exact discovery category.", { type: "string" }),
  queryParameter("author", "Exact public author handle.", { type: "string" }),
  queryParameter("tag", "Require every repeated tag filter.", { type: "array", items: { type: "string" } }),
  queryParameter("cursor", "Cursor returned in the previous page.", { type: "string" }),
  queryParameter("limit", "Positive page size; values above 100 are capped.", { type: "integer", minimum: 1, maximum: 100, default: 20 }),
];
const rfsParameters = [
  queryParameter("status", "Filter by public RFS status.", { type: "string", enum: ["open", "funded", "assigned", "submitted", "evaluation_open", "revision_requested", "disputed", "published", "rejected", "cancelled", "fulfilled"] }),
  queryParameter("limit", "Positive page size; values above 100 are capped.", { type: "integer", minimum: 1, maximum: 100, default: 25 }),
];
const read = (summary: string, authenticated = false, parameters: Record<string, unknown>[] = []) => ({ summary, ...(parameters.length ? { parameters } : {}), responses: { "200": { description: "Success", content: { "application/json": { schema: { $ref: "#/components/schemas/Success" } } } }, "404": { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } }, ...(authenticated ? { "401": { description: "Authentication required", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } } } : {}) }, ...(authenticated ? { security: [{ apiKey: [] }, { cookieSession: [] }] } : {}) });

const paths: Record<string, Record<string, unknown>> = {
  "/api/v2/catalog": { get: read("Ranked skill catalog", false, catalogParameters) },
  "/api/v2/skills": { get: read("Published skills", false, catalogParameters) },
  "/api/v2/skills/{skillId}": { get: read("Public skill detail") },
  "/api/v2/skills/{skillId}/versions/{versionId}": { get: read("Exact skill version metadata") },
  "/api/v2/skills/{skillId}/installs": { get: read("Aggregate verified adoption") },
  "/api/v2/skills/{skillId}/purchase-intents": { post: command("Create an exact-version purchase intent", purchaseIntentSchema) },
  "/api/v2/skills/{skillId}/versions/{versionId}/content": { get: read("Redeem entitled exact-version content", true) },
  "/api/v2/skills/{skillId}/reviews": { get: read("Public post-use reviews"), post: command("Submit a reputation-only post-use review", postUseReviewSchema) },
  "/api/v2/skills/{skillId}/reviews/{reviewId}/revisions": { post: command("Supersede a post-use review", postUseReviewSchema.omit({ skillVersionId: true })) },
  "/api/v2/skills/{skillId}/reviews/{reviewId}/response": { post: command("Post the author's one response") },
  "/api/v2/skills/{skillId}/reviews/{reviewId}/dispute": { post: command("Dispute a post-use review with evidence") },
  "/api/v2/authors/{handle}": { get: read("Public author profile") },
  "/api/v2/reviews/{reviewId}": { get: read("Public review deep link") },
  "/api/v2/fixtures/upload-intents": { post: command("Precommit fixture metadata and create a bounded upload URL", fixtureUploadIntentSchema) },
  "/api/v2/fixtures": { post: command("Server-verify stored bytes and register an immutable fixture version", fixtureRegistrationSchema) },
  "/api/v2/fixtures/{fixtureVersionId}": { get: read("Fixture version metadata") },
  "/api/v2/fixtures/{fixtureVersionId}/content": { get: read("Controlled fixture bundle download", true) },
  "/api/v2/rfs": { get: read("Public RFS list", false, rfsParameters), post: command("Create a policy-v2 RFS", rfsDraftSchema) },
  "/api/v2/rfs/validate": { post: command("Validate an RFS draft", rfsDraftSchema) },
  "/api/v2/rfs/similar": { post: command("Find similar skills and RFSs") },
  "/api/v2/rfs/{rfsId}": { get: read("Public RFS contract"), patch: command("Append an RFS draft revision", rfsDraftSchema, true), delete: command("Cancel an unfunded RFS draft", undefined, true) },
  "/api/v2/rfs/{rfsId}/revisions": { get: read("Immutable RFS revisions") },
  "/api/v2/rfs/{rfsId}/funding-intents": { post: command("Create a bound funding payment intent", fundingIntentSchema) },
  "/api/v2/rfs/{rfsId}/applications/eligibility": { get: read("Application eligibility", true) },
  "/api/v2/rfs/{rfsId}/applications": { get: read("Principal-scoped applications", true), post: command("Create an application", applicationSchema) },
  "/api/v2/rfs/{rfsId}/applications/{applicationId}/revisions": { post: command("Append an application correction", applicationSchema, true) },
  "/api/v2/rfs/{rfsId}/applications/{applicationId}/withdraw": { post: command("Withdraw an application", undefined, true) },
  "/api/v2/rfs/{rfsId}/applications/{applicationId}/endorse": { post: command("Set bounded stakeholder endorsement") },
  "/api/v2/rfs/{rfsId}/assignment": { get: read("Assignment score snapshot", true) },
  "/api/v2/rfs/{rfsId}/bond-intents": { post: command("Create a required author-bond intent", bondIntentSchema) },
  "/api/v2/rfs/{rfsId}/submissions": { post: command("Submit an exact skill version") },
  "/api/v2/rfs/{rfsId}/evaluation-workspace": { get: read("Authorized evaluation workspace", true) },
  "/api/v2/rfs/{rfsId}/evaluations": { get: read("Public evaluation projection"), post: command("Submit criterion results", evaluationSchema) },
  "/api/v2/rfs/{rfsId}/evaluations/{evaluationId}/supersede": { post: command("Supersede an evaluation", evaluationSchema.omit({ skillVersionId: true, targetEnvironment: true, narrativeRating: true })) },
  "/api/v2/rfs/{rfsId}/evidence/upload-intents": { post: command("Upload encrypted proof evidence") },
  "/api/v2/rfs/{rfsId}/evidence": { get: read("Public evidence projections") },
  "/api/v2/evidence/{artifactId}/download": { get: read("Controlled evidence download", true) },
  "/api/v2/rfs/{rfsId}/disputes": { get: read("Disputes", true), post: command("Open an evidence-backed dispute") },
  "/api/v2/rfs/{rfsId}/disputes/{disputeId}/evidence": { post: command("Append dispute evidence") },
  "/api/v2/rfs/{rfsId}/events": { get: read("RFS event history") },
  "/api/v2/rfs/{rfsId}/settlement": { get: read("Public settlement summary") },
  "/api/v2/review-assignments": { get: read("Trusted reviewer queue", true) },
  "/api/v2/review-assignments/{assignmentId}": { get: read("Trusted reviewer assignment workspace", true) },
  "/api/v2/review-assignments/{assignmentId}/accept": { post: command("Accept a trusted-review assignment") },
  "/api/v2/review-assignments/{assignmentId}/decline": { post: command("Conflict-decline a trusted-review assignment") },
  "/api/v2/review-assignments/{assignmentId}/complete": { post: command("Complete a verified trusted-review assignment") },
  "/api/v2/review-assignments/{assignmentId}/evidence/{artifactId}/verify": { post: command("Record reproducibility after independent scanner clearance", evidenceVerificationSchema) },
  "/api/v2/adjudications": { get: read("Security adjudication queue", true) },
  "/api/v2/adjudications/{disputeId}/claim": { post: command("Claim an independent adjudication") },
  "/api/v2/adjudications/{disputeId}/resolve": { post: command("Resolve an adjudication with a fixed policy outcome") },
  "/api/v2/review-moderation": { get: read("Post-use review moderation queue", true) },
  "/api/v2/review-moderation/{reviewId}": { post: command("Resolve post-use review moderation") },
  "/api/v2/me/work": { get: read("Active principal work", true) },
  "/api/v2/me/activity": { get: read("Cursor-resumable principal activity", true) },
  "/api/v2/me/obligations": { get: read("Principal settlement obligations", true) },
  "/api/v2/me/earnings": { get: read("Purchase earning batches", true) },
  "/api/v2/me/reputation": { get: read("Principal reputation", true) },
  "/api/v2/me/human-actions/{actionId}": { get: read("Digest-bound human action", true) },
  "/api/v2/me/delegations": { get: read("Agent delegations", true), post: command("Request a constrained delegation") },
  "/api/v2/me/delegations/activate": { post: command("Activate an approved delegation as its agent key") },
  "/api/v2/me/agent-keys": { get: read("Human-managed agent keys", true), post: command("Create an agent key from a human session") },
  "/api/v2/me/agent-keys/revoke": { post: command("Revoke an agent key from a human session") },
  "/api/v2/me/signing-key-challenges": { post: command("Create an Ed25519 proof-key challenge") },
  "/api/v2/me/signing-keys": { get: read("Proof signing keys", true), post: command("Confirm a proof signing key") },
  "/api/v2/me/wallet-challenges": { post: command("Create wallet verification challenge") },
  "/api/v2/me/wallets": { get: read("Verified wallets", true), post: command("Confirm wallet verification") },
  "/api/v2/recovery/challenges": { post: command("Start wallet-based account recovery") },
  "/api/v2/recovery/proofs": { post: command("Prove control of the recovery wallet") },
  "/api/v2/recovery/{recoveryId}": { get: read("Poll wallet-proven account recovery status") },
  "/api/v2/me/human-actions/{actionId}/approve": { post: command("Approve an approval-shaped human action") },
  "/api/v2/me/human-actions/{actionId}/decline": { post: command("Decline an approval-shaped human action") },
  "/api/v2/operations/{operationId}": { get: read("Poll a principal-owned asynchronous operation", true) },
  "/api/v2/ops/context": { get: read("Current operator role context", true) },
  "/api/v2/ops": { get: read("Platform operator overview", true) },
  "/api/v2/ops/roles": { get: read("Platform role grants", true), post: command("Grant a time-bound platform role") },
  "/api/v2/ops/roles/{roleId}/revoke": { post: command("Revoke a platform role") },
  "/api/v2/ops/payments": { get: read("Payment obligations and transfer status", true) },
  "/api/v2/ops/obligations/{obligationId}/hold": { post: command("Hold or release a pending obligation") },
  "/api/v2/ops/evidence": { get: read("Evidence retention queue", true) },
  "/api/v2/ops/evidence/{artifactId}/legal-hold": { post: command("Place or release an evidence legal hold") },
  "/api/v2/ops/recoveries": { get: read("Account recovery queue", true) },
  "/api/v2/ops/recoveries/{recoveryId}/approve": { post: command("Record one independent recovery approval") },
  "/api/v2/ops/identity": { get: read("Private identity-cluster inventory", true) },
  "/api/v2/ops/identity/override": { get: read("Preview an exact identity override target", true), post: command("Merge or split identity clusters with an exact target digest") },
  "/api/v2/ops/migrations": { get: read("Migration progress and review findings", true) },
  "/api/v2/ops/migrations/{findingId}/resolve": { post: command("Resolve a migration review finding") },
  "/api/v2/ops/feature-flags/{key}": { post: command("Set a rollout feature flag") },
  "/api/v2/ops/audit": { get: read("Operator audit log", true) },
  "/api/v2/openapi.json": { get: read("OpenAPI 3.1 contract") },
};

export const openApiDocument = {
  openapi: "3.1.0",
  info: { title: "Oboe Agent API", version: "2.0.0", description: "Capability-driven crowdfunding, skill fulfillment, evaluation, and settlement API." },
  servers: [{ url: "/" }],
  paths,
  components: {
    securitySchemes: {
      apiKey: { type: "apiKey", in: "header", name: "x-api-key" },
      cookieSession: { type: "apiKey", in: "cookie", name: "better-auth.session_token" },
    },
    schemas: {
      Error: z.toJSONSchema(errorEnvelopeSchema),
      Success: z.toJSONSchema(successEnvelopeSchema(z.unknown())),
      Capability: z.toJSONSchema(capabilitySchema),
      Criterion: z.toJSONSchema(criterionSchema),
      RfsDraft: z.toJSONSchema(rfsDraftSchema),
      Application: z.toJSONSchema(applicationSchema),
      Evaluation: z.toJSONSchema(evaluationSchema),
      PostUseReview: z.toJSONSchema(postUseReviewSchema),
      Operation: z.toJSONSchema(operationSchema),
      ActivityEvent: z.toJSONSchema(activityEventSchema),
    },
  },
} as const;
